# Site settings
title: HackerFood
email: info@hackerfood.com
description: > # this means to ignore newlines until "baseurl:"
  We write about food for hackathons.
baseurl: "/hackerfood" # the subpath of your site, e.g. /blog/
url: "http://hackersofamsterdam.github.io" # the base hostname & protocol for your site
twitter_username: hackersofamsterdam
github_username:  hackersofamsterdam

# Build settings
markdown: kramdown

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: HackerFood
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Food for Hackers" # used by search engines

  # Header and footer text
  header_text: >
     <p>Hackathons ain't no fun without food. That's what we thing, and that's why we blog about the best food for hackathons.</p>
  header_text_feature_image:
  footer_text: >
    This is a blog used to show the audience what our advertising service can do.

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "hackersofamsterdam/hackerfood"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "amsterdamhacker"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false
